import { Exercise } from "./interfaces";

export const exercises: Exercise[] = [
  {
    id: "cmotyc9v50000qovufxwc4enk",
    name: "Tadasana (Mountain Pose)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Flexibility",
    description:
      "Seedhe khade hokar body ko align karo aur deep breathing karo; posture improve karne aur body awareness badhane ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 2,
  },
  {
    id: "cmotycb3b0001qovumu7giqfn",
    name: "Vrikshasana (Tree Pose)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Balance",
    description:
      "Ek pair par balance karke dusra pair thigh par rakho; focus aur stability improve karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 2.5,
  },
  {
    id: "cmotycc9m0002qovuwqwilzdw",
    name: "Surya Namaskar (Beginner)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Flexibility",
    description:
      "Slow pace me 12 yoga steps follow karo; body warm-up aur flexibility badhane ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 4,
  },
  {
    id: "cmotycdhe0003qovubdxeupbx",
    name: "Surya Namaskar (Intermediate)",
    category: "Yoga",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Thoda fast flow me rounds complete karo; calorie burn aur metabolism boost karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 20,
    caloriesPerMin: 6,
  },
  {
    id: "cmotycep90004qovuvrm8kt77",
    name: "Adho Mukha Svanasana (Downward Dog)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Flexibility",
    description:
      "Body ko inverted V shape me le jao; full body stretch aur flexibility improve karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 3.5,
  },
  {
    id: "cmotycft10005qovukqvukdqo",
    name: "Balasana (Child's Pose)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Recovery",
    description:
      "Knees fold karke forward bend me rest karo; relaxation aur stress relief ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 1.5,
  },
  {
    id: "cmotycgwp0006qovukd94pcab",
    name: "Virabhadrasana I (Warrior I)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Strength",
    description:
      "Lunge position me arms upar uthao; legs aur core strength badhane ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 4.5,
  },
  {
    id: "cmotyci0g0007qovudp2y3tux",
    name: "Virabhadrasana II (Warrior II)",
    category: "Yoga",
    difficulty: "Intermediate",
    goal: "Strength",
    description:
      "Side facing stance me arms stretch karo; endurance aur balance improve karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 5,
  },
  {
    id: "cmotycj5a0008qovu0kuanoeq",
    name: "Trikonasana (Triangle Pose)",
    category: "Yoga",
    difficulty: "Intermediate",
    goal: "Flexibility",
    description:
      "Side bend karke ek haath niche aur ek upar rakho; spine stretch aur flexibility ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 8,
    caloriesPerMin: 4,
  },
  {
    id: "cmotyck9p0009qovuj3kmgb7o",
    name: "Bhujangasana (Cobra Pose)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Flexibility",
    description:
      "Pet ke bal lete hue chest upar uthao; spine strengthen aur posture improve karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 3,
  },
  {
    id: "cmotycle3000aqovua9lpq71x",
    name: "Ashtanga Yoga Flow",
    category: "Yoga",
    difficulty: "Advanced",
    goal: "Weight Loss",
    description:
      "Continuous dynamic yoga flow follow karo; stamina aur fat loss ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 45,
    caloriesPerMin: 8.5,
  },
  {
    id: "cmotycmhy000bqovup7ojty58",
    name: "Paschimottanasana",
    category: "Yoga",
    difficulty: "Intermediate",
    goal: "Flexibility",
    description:
      "Baithkar forward bend karo aur toes pakdo; hamstrings aur spine stretch ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 3,
  },
  {
    id: "cmotycnn6000cqovuhqrkannc",
    name: "Bakasana (Crow Pose)",
    category: "Yoga",
    difficulty: "Advanced",
    goal: "Strength",
    description:
      "Hands par body balance karo; core aur arm strength build karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 6,
  },
  {
    id: "cmotycor6000dqovuj1z71c2i",
    name: "Setu Bandhasana (Bridge Pose)",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Recovery",
    description:
      "Back ke bal lete hue hips upar uthao; glutes strengthen aur relaxation ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 3.5,
  },
  {
    id: "cmotycpwa000eqovu06qeax27",
    name: "Savasana",
    category: "Yoga",
    difficulty: "Beginner",
    goal: "Recovery",
    description:
      "Seedha letkar body ko completely relax karo; recovery aur stress relief ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1,
  },
  {
    id: "cmotycr0b000fqovuv4xulzho",
    name: "Knee Pushups",
    category: "Strength",
    difficulty: "Beginner",
    goal: "Muscle Gain",
    description:
      "Knees ground par rakhkar pushups karo; beginner upper body strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 10,
    recommendedDuration: 0,
    caloriesPerMin: 5,
  },
  {
    id: "cmotycs5f000gqovuzxmtciq4",
    name: "Standard Pushups",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Muscle Gain",
    description:
      "Straight body position me pushups karo; chest aur triceps build karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 15,
    recommendedDuration: 0,
    caloriesPerMin: 8,
  },
  {
    id: "cmotyct9z000hqovu6i51de40",
    name: "Diamond Pushups",
    category: "Strength",
    difficulty: "Advanced",
    goal: "Muscle Gain",
    description:
      "Hands close rakhkar pushups karo; triceps focus aur strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 0,
    caloriesPerMin: 10,
  },
  {
    id: "cmotycufc000iqovu8huxaunr",
    name: "Bodyweight Squats",
    category: "Strength",
    difficulty: "Beginner",
    goal: "Muscle Gain",
    description:
      "Khade hokar hips niche le jao aur utho; legs aur glutes strong karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 15,
    recommendedDuration: 30,
    caloriesPerMin: 6,
  },
  {
    id: "cmotycvjy000jqovuuqgxbfog",
    name: "Jump Squats",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Squat ke baad jump karo; explosive power aur calorie burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 30,
    caloriesPerMin: 11,
  },
  {
    id: "cmotycwos000kqovudpyl09fc",
    name: "Walking Lunges",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Muscle Gain",
    description:
      "Forward step lete hue lunges karo; balance aur leg strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 20,
    recommendedDuration: 30,
    caloriesPerMin: 7,
  },
  {
    id: "cmotycxsi000lqovub0puowgu",
    name: "Plank (Hold)",
    category: "Strength",
    difficulty: "Beginner",
    goal: "Core Strength",
    description:
      "Elbows par body straight hold karo; core stability aur strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 30,
    caloriesPerMin: 4,
  },
  {
    id: "cmotycyxv000mqovuvmle3jhn",
    name: "Side Plank",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Core Strength",
    description:
      "Side par body hold karo; obliques aur balance improve karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 30,
    caloriesPerMin: 5,
  },
  {
    id: "cmotyd042000nqovujw6va3zq",
    name: "Burpees",
    category: "Strength",
    difficulty: "Advanced",
    goal: "Weight Loss",
    description:
      "Squat + pushup + jump combo karo; full body fat burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 10,
    recommendedDuration: 30,
    caloriesPerMin: 13,
  },
  {
    id: "cmotyd19i000oqovuz0s4v48p",
    name: "Mountain Climbers",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Plank position me legs alternate move karo; cardio aur core ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 2,
    caloriesPerMin: 10,
  },
  {
    id: "cmotyd2dj000pqovuzj0nwbd7",
    name: "Pull Ups",
    category: "Strength",
    difficulty: "Advanced",
    goal: "Muscle Gain",
    description:
      "Bar pakadkar body upar kheecho; back aur arms build karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 8,
    recommendedDuration: 10,
    caloriesPerMin: 9,
  },
  {
    id: "cmotyd3iu000qqovu7ykjcxu1",
    name: "Tricep Dips",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Muscle Gain",
    description:
      "Bench ya chair par dips karo; triceps strengthen karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 22,
    caloriesPerMin: 6.5,
  },
  {
    id: "cmotyd4ok000rqovuohxaydgo",
    name: "Dumbbell Bicep Curls",
    category: "Strength",
    difficulty: "Beginner",
    goal: "Muscle Gain",
    description:
      "Dumbbells uthakar curls karo; biceps muscle build karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 16,
    caloriesPerMin: 4,
  },
  {
    id: "cmotyd5su000sqovu4e6vq7p0",
    name: "Deadlifts (Form Focus)",
    category: "Strength",
    difficulty: "Advanced",
    goal: "Muscle Gain",
    description:
      "Weight ko ground se upar uthao proper form ke saath; full body strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 8,
    recommendedDuration: 16,
    caloriesPerMin: 11,
  },
  {
    id: "cmotyd6wj000tqovudioxfskj",
    name: "Hollow Body Hold",
    category: "Strength",
    difficulty: "Intermediate",
    goal: "Core Strength",
    description:
      "Back par letkar core tight hold karo; abs strength aur control ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 1,
    caloriesPerMin: 4.5,
  },
  {
    id: "cmotyd812000uqovugddc4c7p",
    name: "Brisk Walking",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Maintenance",
    description:
      "Tez pace me walk karo; heart health aur calorie burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 30,
    caloriesPerMin: 4.5,
  },
  {
    id: "cmotyd97c000vqovuv1848khn",
    name: "Jogging",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Weight Loss",
    description:
      "Light running karo steady pace me; stamina aur fat loss ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 20,
    caloriesPerMin: 8,
  },
  {
    id: "cmotydadv000wqovutnadepkw",
    name: "Sprinting (HIIT)",
    category: "Cardio",
    difficulty: "Advanced",
    goal: "Weight Loss",
    description: "Short bursts me fast run karo; maximum calorie burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 15,
  },
  {
    id: "cmotydblg000xqovuo50kgz8y",
    name: "Jumping Jacks",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Weight Loss",
    description:
      "Jump karke arms aur legs spread karo; warm-up aur cardio ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 9,
  },
  {
    id: "cmotydctt000yqovufklynzq4",
    name: "Skipping Rope (Slow)",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Weight Loss",
    description: "Rope se slow jumps karo; coordination aur stamina ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 10,
  },
  {
    id: "cmotyddxb000zqovuqewegf2a",
    name: "Skipping Rope (Double Unders)",
    category: "Cardio",
    difficulty: "Advanced",
    goal: "Weight Loss",
    description:
      "Ek jump me rope do baar ghumao; high intensity fat burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 16,
  },
  {
    id: "cmotydf1k0010qovubcewmb4a",
    name: "High Knees",
    category: "Cardio",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Running position me knees high uthao; cardio aur leg strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 11,
  },
  {
    id: "cmotydg5s0011qovupugq77lh",
    name: "Butt Kicks",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Weight Loss",
    description:
      "Heels ko hips tak le jao running me; warm-up aur flexibility ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 8,
  },
  {
    id: "cmotydha40012qovubjj8fdvs",
    name: "Cycling (Moderate)",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Maintenance",
    description:
      "Moderate speed me cycle chalao; endurance aur leg strength ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 40,
    caloriesPerMin: 7,
  },
  {
    id: "cmotydif70013qovu888k8q2t",
    name: "Cycling (Uphill)",
    category: "Cardio",
    difficulty: "Advanced",
    goal: "Muscle Gain",
    description: "Chadhai par cycling karo; legs power aur stamina ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 20,
    caloriesPerMin: 12,
  },
  {
    id: "cmotydjj70014qovu064dfkmi",
    name: "Swimming (Freestyle)",
    category: "Cardio",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Freestyle stroke me swim karo; full body workout aur fat loss ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 10,
  },
  {
    id: "cmotydkn70015qovu8bvk6jgg",
    name: "Stair Climbing",
    category: "Cardio",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Stairs par up-down movement karo; intense calorie burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 12,
  },
  {
    id: "cmotydlrm0016qovuuvj3xyb0",
    name: "Shadow Boxing",
    category: "Cardio",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description:
      "Air punches practice karo; agility aur cardio fitness ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 9,
  },
  {
    id: "cmotydmyi0017qovu6tdurkwj",
    name: "Elliptical Trainer",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Maintenance",
    description: "Machine par smooth movement karo; low impact cardio ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 6.5,
  },
  {
    id: "cmotydo280018qovuhz99u5da",
    name: "Dancing (Zumba Style)",
    category: "Cardio",
    difficulty: "Beginner",
    goal: "Weight Loss",
    description:
      "Music ke sath dance moves karo; fun way me calorie burn ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 12,
    caloriesPerMin: 7.5,
  },
  {
    id: "cmotydp9k0019qovu0nb08lmb",
    name: "Breath Awareness Meditation",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Mental Health",
    description:
      "Shant baithkar breath observe karo; mind calm aur awareness ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1,
  },
  {
    id: "cmotydqf1001aqovup4mki4bz",
    name: "Anulom Vilom (Pranayama)",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Mental Health",
    description:
      "Alternate nostril breathing karo; stress reduce aur lungs improve ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1.5,
  },
  {
    id: "cmotydrj9001bqovu2p6of96f",
    name: "Kapalbhati",
    category: "Meditation",
    difficulty: "Intermediate",
    goal: "Weight Loss",
    description: "Forceful exhalation practice karo; metabolism boost ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 3.5,
  },
  {
    id: "cmotydsri001cqovuocxuuyr8",
    name: "Bhramari Pranayama (Bee Breath)",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Mental Health",
    description:
      "Humming sound ke sath breathing karo; anxiety reduce ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 5,
    caloriesPerMin: 1.2,
  },
  {
    id: "cmotydtvy001dqovuo7xy9tkf",
    name: "Box Breathing",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Focus",
    description:
      "4-4-4-4 pattern me inhale-hold-exhale karo; focus improve ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 8,
    caloriesPerMin: 1,
  },
  {
    id: "cmotydv3u001eqovuwvewoxva",
    name: "Guided Mindfulness Meditation",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Mental Health",
    description:
      "Audio guidance ke sath meditation karo; relaxation aur clarity ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 1,
  },
  {
    id: "cmotydwg8001fqovu7bn05epz",
    name: "Body Scan Meditation",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Recovery",
    description:
      "Body parts par dhyan le jao; tension release aur awareness ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 20,
    caloriesPerMin: 1,
  },
  {
    id: "cmotydxo5001gqovuzoivhx53",
    name: "Loving-Kindness (Metta) Meditation",
    category: "Meditation",
    difficulty: "Intermediate",
    goal: "Mental Health",
    description:
      "Positive thoughts aur compassion practice karo; emotional health ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 1,
  },
  {
    id: "cmotydytl001hqovuy4382pqp",
    name: "Deep Belly Breathing",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Recovery",
    description:
      "Deep abdominal breathing karo; stress relief aur relaxation ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1.2,
  },
  {
    id: "cmotydzyw001iqovu7gaomncp",
    name: "Zen Meditation (Zazen)",
    category: "Meditation",
    difficulty: "Advanced",
    goal: "Focus",
    description:
      "Still baithkar awareness maintain karo; discipline aur focus ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1,
  },
  {
    id: "cmotye13d001jqovu53xhmeet",
    name: "Visualisation Meditation",
    category: "Meditation",
    difficulty: "Intermediate",
    goal: "Focus",
    description:
      "Mind me positive images imagine karo; goal clarity aur focus ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 15,
    caloriesPerMin: 1,
  },
  {
    id: "cmotye27y001kqovurxaaesb2",
    name: "Walking Meditation",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Mental Health",
    description: "Slow mindful walking karo; mind-body connection ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 20,
    caloriesPerMin: 3,
  },
  {
    id: "cmotye3c8001lqovua3m0or77",
    name: "Yoga Nidra",
    category: "Meditation",
    difficulty: "Advanced",
    goal: "Mental Health",
    description:
      "Guided deep relaxation me jao; mental recovery aur stress relief ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 30,
    caloriesPerMin: 1,
  },
  {
    id: "cmotye4h7001mqovutw1luh0m",
    name: "OM Chanting",
    category: "Meditation",
    difficulty: "Beginner",
    goal: "Mental Health",
    description: "OM sound chant karo; vibration se mind calm karne ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1.8,
  },
  {
    id: "cmotye5lb001nqovu65vaic4y",
    name: "Trataka (Candle Gazing)",
    category: "Meditation",
    difficulty: "Intermediate",
    goal: "Focus",
    description:
      "Candle flame par gaze karo bina blink; concentration improve ke liye.",
    recommendedSets: 3,
    recommendedReps: 12,
    recommendedDuration: 10,
    caloriesPerMin: 1,
  },
];
