import { FoodLibraryType } from "./interfaces";

export const foods: FoodLibraryType[] = [
  {
    id: "043d63a2-cfcc-4cb5-9dbf-7c740cc501fa",
    foodName: "Whole Eggs",
    calories: 155,
    protein: 13,
    carbs: 1,
    fats: 11,
    mealType: "breakfast",
    quantity: "3 eggs",
    goals: ["WeightGain"],
    description: "Whole eggs khao; protein aur calories dono ke liye.",
  },
  {
    id: "14d8b6f1-734b-40b3-87cf-86610dcde7e3",
    foodName: "Peanut Butter",
    calories: 190,
    protein: 8,
    carbs: 6,
    fats: 16,
    mealType: "breakfast",
    quantity: "2 tbsp",
    goals: ["WeightGain"],
    description: "Peanut butter lo; high calories aur healthy fats ke liye.",
  },
  {
    id: "17926687-0ca4-44ed-9711-cf98b7f1b46a",
    foodName: "Salad",
    calories: 80,
    protein: 2,
    carbs: 10,
    fats: 2,
    mealType: "lunch",
    quantity: "1 bowl",
    goals: ["Common"],
    description: "Fresh salad khao; vitamins aur fiber ke liye.",
  },
  {
    id: "17cc92b1-f763-49e0-ad8f-70a1f2cca721",
    foodName: "Banana Shake",
    calories: 300,
    protein: 8,
    carbs: 50,
    fats: 8,
    mealType: "snack",
    quantity: "1 glass",
    goals: ["WeightGain"],
    description: "Banana shake piyo; fast weight gain ke liye.",
  },
  {
    id: "2495f760-0fd9-448a-88bd-811511bbd105",
    foodName: "Rice",
    calories: 200,
    protein: 4,
    carbs: 45,
    fats: 1,
    mealType: "lunch",
    quantity: "1 bowl",
    goals: ["Common"],
    description: "Chawal lo; quick energy aur carb intake ke liye.",
  },
  {
    id: "2efc3c8a-5a06-4bb3-a31d-5e610b8f1449",
    foodName: "Boiled Egg",
    calories: 78,
    protein: 6,
    carbs: 1,
    fats: 5,
    mealType: "breakfast",
    quantity: "2 eggs",
    goals: ["WeightLoss"],
    description: "Uble ande lo; high protein aur fat loss ke liye.",
  },
  {
    id: "3fef116b-f5da-41a6-83e5-c113dc23df7e",
    foodName: "Banana",
    calories: 105,
    protein: 1,
    carbs: 27,
    fats: 0,
    mealType: "snack",
    quantity: "1 banana",
    goals: ["Common"],
    description: "Kela lo; instant energy aur potassium ke liye.",
  },
  {
    id: "4e42279d-29f6-453b-9874-d24790602d92",
    foodName: "Grilled Chicken",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3,
    mealType: "lunch",
    quantity: "100g",
    goals: ["WeightLoss"],
    description: "Grilled chicken khaao; lean protein ke liye.",
  },
  {
    id: "4eac9b2a-9eb4-43b7-a883-e93582c83f4e",
    foodName: "Brown Rice",
    calories: 215,
    protein: 5,
    carbs: 45,
    fats: 2,
    mealType: "lunch",
    quantity: "1 bowl",
    goals: ["WeightLoss"],
    description: "Brown rice lo; fiber-rich carbs ke liye.",
  },
  {
    id: "5b0ada02-4136-478e-9c6d-aac562ce7cb9",
    foodName: "Apple",
    calories: 95,
    protein: 0,
    carbs: 25,
    fats: 0,
    mealType: "snack",
    quantity: "1 apple",
    goals: ["Common"],
    description: "Seb khao; fiber aur immunity ke liye.",
  },
  {
    id: "65653d7d-8c2c-4323-8499-19137b15ba01",
    foodName: "Green Tea",
    calories: 2,
    protein: 0,
    carbs: 0,
    fats: 0,
    mealType: "snack",
    quantity: "1 cup",
    goals: ["Common"],
    description:
      "Green tea piyo; metabolism boost aur fat burn support ke liye.",
  },
  {
    id: "6e1f4321-e26b-480e-95ad-cd96a6231ac1",
    foodName: "Curd (Dahi)",
    calories: 98,
    protein: 11,
    carbs: 4,
    fats: 4,
    mealType: "lunch",
    quantity: "1 bowl",
    goals: ["Common"],
    description: "Dahi khao; digestion aur gut health ke liye.",
  },
  {
    id: "6fef9db7-f67f-4d72-99b8-647f477ac270",
    foodName: "Chicken Curry",
    calories: 280,
    protein: 25,
    carbs: 5,
    fats: 18,
    mealType: "lunch",
    quantity: "1 bowl",
    goals: ["WeightGain"],
    description: "Chicken curry lo; protein aur calorie surplus ke liye.",
  },
  {
    id: "739f37a7-d1c3-4d2b-9f32-e2e1c514361e",
    foodName: "Black Coffee",
    calories: 5,
    protein: 0,
    carbs: 0,
    fats: 0,
    mealType: "snack",
    quantity: "1 cup",
    goals: ["WeightLoss"],
    description: "Black coffee piyo; fat burn aur alertness ke liye.",
  },
  {
    id: "8662ffb6-95fa-46ef-93ab-7f3b9653ad3b",
    foodName: "Cucumber",
    calories: 30,
    protein: 1,
    carbs: 6,
    fats: 0,
    mealType: "snack",
    quantity: "1 plate",
    goals: ["WeightLoss"],
    description: "Kheera lo; hydration aur low calories ke liye.",
  },
  {
    id: "8a2223ec-1b38-4457-85b2-4eca7114bee5",
    foodName: "Paneer",
    calories: 265,
    protein: 18,
    carbs: 2,
    fats: 20,
    mealType: "dinner",
    quantity: "100g",
    goals: ["WeightGain"],
    description: "Paneer lo; calories aur protein dono ke liye.",
  },
  {
    id: "8a3b3a92-5b75-42b9-9611-9ed40f4c5639",
    foodName: "Cheese",
    calories: 200,
    protein: 12,
    carbs: 2,
    fats: 16,
    mealType: "snack",
    quantity: "2 slices",
    goals: ["WeightGain"],
    description: "Cheese khao; calorie dense food ke liye.",
  },
  {
    id: "8dfa97e8-1580-411f-8b38-b955f7e60619",
    foodName: "White Rice",
    calories: 250,
    protein: 4,
    carbs: 55,
    fats: 1,
    mealType: "lunch",
    quantity: "1 bowl",
    goals: ["WeightGain"],
    description: "White rice lo; high carbs aur energy ke liye.",
  },
  {
    id: "929d9ed1-dd91-4b8b-b9c6-27b615f0662c",
    foodName: "Vegetable Soup",
    calories: 80,
    protein: 3,
    carbs: 15,
    fats: 1,
    mealType: "dinner",
    quantity: "1 bowl",
    goals: ["WeightLoss"],
    description: "Soup piyo; low calorie aur filling meal ke liye.",
  },
  {
    id: "97fe0bb3-8cfd-4e56-852a-15a195c68c8d",
    foodName: "Water",
    calories: 0,
    protein: 0,
    carbs: 0,
    fats: 0,
    mealType: "anytime",
    quantity: "1 glass",
    goals: ["Common"],
    description:
      "Din bhar pani piyo; hydration aur body functions maintain karne ke liye.",
  },
  {
    id: "a5164b1f-7601-4fb0-87ea-d0ac6bb78ea4",
    foodName: "Oats",
    calories: 150,
    protein: 5,
    carbs: 27,
    fats: 3,
    mealType: "breakfast",
    quantity: "1 bowl",
    goals: ["WeightLoss"],
    description: "Oats khaao; slow carbs aur long-lasting energy ke liye.",
  },
  {
    id: "a697d168-7b41-4471-a94e-e28ff5e728bd",
    foodName: "Almonds",
    calories: 160,
    protein: 6,
    carbs: 6,
    fats: 14,
    mealType: "snack",
    quantity: "10 pieces",
    goals: ["Common"],
    description: "Badam khao; healthy fats aur brain health ke liye.",
  },
  {
    id: "a862e3eb-11f9-47dc-b052-acf2275ae84d",
    foodName: "Full Cream Milk",
    calories: 150,
    protein: 8,
    carbs: 12,
    fats: 8,
    mealType: "night",
    quantity: "1 glass",
    goals: ["WeightGain"],
    description: "Full cream milk piyo; weight gain aur recovery ke liye.",
  },
  {
    id: "ae23dfae-fe50-4788-acff-d4401e2ea6b3",
    foodName: "Chapati",
    calories: 120,
    protein: 3,
    carbs: 20,
    fats: 3,
    mealType: "lunch",
    quantity: "1 roti",
    goals: ["Common"],
    description: "Roti khao; daily energy aur carbs ke liye.",
  },
  {
    id: "b2b1cb10-7617-4afc-a071-3e05b480d2ec",
    foodName: "Milk",
    calories: 120,
    protein: 6,
    carbs: 12,
    fats: 5,
    mealType: "breakfast",
    quantity: "1 glass",
    goals: ["Common"],
    description: "Doodh piyo; calcium aur protein ke liye.",
  },
  {
    id: "c6d3801e-ea87-43a0-aac9-782fc0d22c31",
    foodName: "Dry Fruits Mix",
    calories: 300,
    protein: 6,
    carbs: 20,
    fats: 22,
    mealType: "snack",
    quantity: "1 handful",
    goals: ["WeightGain"],
    description: "Dry fruits lo; healthy fats aur calories ke liye.",
  },
  {
    id: "d53d9032-219f-421d-8df2-93e4c7f33984",
    foodName: "Sprouts",
    calories: 120,
    protein: 9,
    carbs: 20,
    fats: 1,
    mealType: "snack",
    quantity: "1 bowl",
    goals: ["WeightLoss"],
    description: "Sprouts khao; fiber aur protein ke liye.",
  },
  {
    id: "dd4c13ce-9b29-4c29-ba5e-58085441a5e9",
    foodName: "Potatoes",
    calories: 160,
    protein: 4,
    carbs: 37,
    fats: 0,
    mealType: "lunch",
    quantity: "2 potatoes",
    goals: ["WeightGain"],
    description: "Aloo khao; carbs aur calories badhane ke liye.",
  },
  {
    id: "ed2ee874-8d74-4035-9df4-198c0cb437ed",
    foodName: "Paneer (Low Fat)",
    calories: 150,
    protein: 18,
    carbs: 3,
    fats: 8,
    mealType: "lunch",
    quantity: "100g",
    goals: ["WeightLoss"],
    description:
      "Low-fat paneer lo; protein ke saath calories control ke liye.",
  },
  {
    id: "f87169ff-a65b-47f1-943f-f0376024d327",
    foodName: "Boiled Vegetables",
    calories: 90,
    protein: 3,
    carbs: 18,
    fats: 1,
    mealType: "dinner",
    quantity: "1 bowl",
    goals: ["WeightLoss"],
    description: "Boiled sabzi khao; light aur healthy meal ke liye.",
  },
];
